# andean_v3/wrangler.toml
name = "andean-v3"
main = ".open-next/worker.js"
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

routes = [
	{ pattern = "andeanscapes.com/*", zone_name = "andeanscapes.com" },
	{ pattern = "www.andeanscapes.com/*", zone_name = "andeanscapes.com" }
]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "andean-v3"

[env.dev]
name = "andean-v3-dev"